name: 运行hduremote.py

on:
  workflow_dispatch:  # 手动触发

jobs:
  run-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: 下载依赖
        run: pip install requests beautifulsoup4 Flask
      - name: 运行python
        run: python hduremote.py
